version: '3.1'
services:
  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8081:8080
  grafana-xxl:  #optional more functional and creative UI 
    image: monitoringartist/grafana-xxl:latest
    volumes:
     - /mnt/grafana:/var/lib/grafana
    ports:
     - 3000:3000
    environment: 
     - GF_INSTALL_PLUGINS=zabbix
