version: '3.1'
services:
  bean_log:
    # build: .
    image: bean_log:test
    container_name: bean_log
    # network_mode: "host"
    restart: unless-stopped
    ports:
      - 8280:80
    volumes:
      - /mnt/bean_log:/data
