version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:0'
    ports:
      - '8191:80'
      - '443:443'
    volumes:
      - 'dokuwiki_data:/bitnami'
volumes:
  dokuwiki_data:
    driver: local
